# Generated by Django 4.2.20 on 2025-05-09 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='学生姓名')),
                ('class_name', models.CharField(max_length=100, verbose_name='班级名称')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='点名时间')),
            ],
            options={
                'indexes': [models.Index(fields=['student_name'], name='call_attend_student_f11a2c_idx'), models.Index(fields=['class_name', 'student_name'], name='call_attend_class_n_c3414a_idx')],
            },
        ),
    ]
