# Generated by Django 4.2.23 on 2025-07-02 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_question_callrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallRecord',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
